name: Continuos Integration

on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.6.0'
      - name: run install
        run: |
          npm install
